/**
 * Regenerate the launch post's headline numbers from the repo's own pipeline — so every stat in
 * "The State of Agent Traffic on N Real Sites" is reproducible, never hand-typed. Runs core's
 * analyze() over a dataset and prints a markdown block ready to paste into the post.
 *
 *   pnpm post-charts                 # over the sample demo dataset (default)
 *   pnpm post-charts --in <file.jsonl>   # over a real capture / drain export (JSONL)
 *
 * When real multi-site data exists, run this per site (or over a merged export) and drop the
 * numbers in. Until then it proves the harness against the demo dataset.
 */

import { readFileSync } from "node:fs";
import { analyze, normalizeJsonl } from "@footfall/core";

function flag(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const input = flag("in") ?? "fixtures/demo/dashboard-demo.jsonl";
const { events, fieldMap } = normalizeJsonl(readFileSync(input, "utf8"));
if (events.length === 0) {
  console.error(`no valid events in ${input}`);
  process.exit(1);
}

const r = analyze(events, fieldMap, { site: "dataset", siteName: input });

const split = Object.fromEntries(r.trafficSplit.map((t) => [t.class, t]));
const agentSessions = split.agent?.sessions ?? 0;
const deadEndSessions = new Set(
  r.failures.filter((f) => f.type === "dead_end").flatMap((f) => f.sessionIds),
).size;
const topDemand = [...r.demand].sort((a, b) => b.count - a.count)[0];

let accuracy: {
  overallAccuracy?: number;
  unclassifiedRate?: number;
  tier1?: { precision?: number };
} = {};
try {
  accuracy = JSON.parse(readFileSync("fixtures/golden/accuracy-baseline.json", "utf8"));
} catch {
  /* baseline optional */
}

const pct = (n: number) => `${n}%`;
const lines = [
  `## Numbers — ${input} (regenerated by \`pnpm post-charts\`)`,
  "",
  `- **Requests:** ${r.meta.totalRequests.toLocaleString()} over ${r.daily.length} day(s)`,
  `- **Agent share of traffic:** ${pct(r.agentSharePct)} (agents ${split.agent?.requests ?? 0}, humans ${split.human?.requests ?? 0}, crawlers ${split.crawler?.requests ?? 0}, unclassified ${split.unclassified?.requests ?? 0})`,
  `- **Agent families:** ${r.families.map((f) => `${f.family} ${f.requests}${f.heuristic ? " (HEURISTIC)" : ""}`).join(", ") || "none"}`,
  `- **Impersonation caught (spoofed crawler):** ${r.spoofedRequests} request(s)`,
  `- **Failed agent requests:** dead_end ${r.failureTotals.dead_end}, auth_wall ${r.failureTotals.auth_wall}, retry_loop ${r.failureTotals.retry_loop}, empty_shell ${r.failureTotals.empty_shell}${r.failureTotals.empty_shell_available ? " (HEURISTIC)" : " (unavailable)"}`,
  `- **Agent sessions hitting a dead end:** ${deadEndSessions} of ${agentSessions}${agentSessions ? ` (${Math.round((deadEndSessions / agentSessions) * 100)}%)` : ""}`,
  topDemand
    ? `- **Most-requested path that 404s:** ${topDemand.path} — ${topDemand.count} request(s), ${topDemand.agentHits} from agents`
    : "- **Most-requested path that 404s:** none",
  "",
  `### Methodology (published)`,
  `- Classifier accuracy (labelled corpus): overall ${accuracy.overallAccuracy != null ? pct(Math.round(accuracy.overallAccuracy * 100)) : "n/a"}, Tier-1 UA precision ${accuracy.tier1?.precision != null ? pct(Math.round(accuracy.tier1.precision * 100)) : "n/a"}.`,
  `- Unclassified rate: ${pct(split.unclassified?.pct ?? 0)} — never force-assigned.`,
  `- Caveats: request-share ≠ user-share; sample skew (dev-facing sites); heuristic signals flagged above.`,
];

console.log(lines.join("\n"));
